fragment UserSettingsFields on UserSetting {
  id
  currency
  timezone
  locale
  theme
  geminiApiKey
  createdAt
  updatedAt
  defaultAccount {
    id
    name
    icon
  }
}

query GetUserSettings($userId: JSON) {
  UserSettings(limit: 1, where: { user: { equals: $userId } }) {
    docs {
      ...UserSettingsFields
    }
  }
}

mutation UpdateUserSettings($id: String!, $data: mutationUserSettingUpdateInput!) {
  updateUserSetting(id: $id, data: $data) {
    ...UserSettingsFields
  }
}
